language: python
sudo: false
compiler:
  - clang
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - cmake
    - libeigen3-dev
install:
  - "pip install -r requirements.txt"
  - "CC=clang CXX=clang++ pip install ."
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  - make
  - cd ..
script: 
  - for f in build/pyQCD/test_*; do ./$f; done
  - py.test -vl
cache:
  directories:
  - $HOME/virtualenv
