language: python
sudo: false
compiler:
  - clang
python:
  - "2.7"
#  - "3.4"
addons:
  apt:
    packages:
    - cmake
    - libeigen3-dev
    - libopenmpi-dev
before_install:
  - pip install pip-accel
install:
  - pip-accel install -r requirements.txt
  - "pip install ."
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  - make
  - cd ..
script: 
  - for f in build/pyQCD/test_*; do echo "Running test file ${f}"; ./$f; done
  - py.test -vl
cache:
  directories:
  - $HOME/.pip-accel
