language: python
compiler:
  - clang
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev
install:
  - "pip install -r requirements.txt"
  - "CC=clang CXX=clang++ pip intall ."
script: py.test
