language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev
install:
  - "pip install -r requirements.txt"
  - "python setup.py build_ext --inplace"
script: py.test
