language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - libeigen3-dev
before_install:
  - pip install pip-accel
install:
  - pip-accel install -r requirements.txt
  - "CC=gcc-5 CXX=g++-5 pip install ."
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
  - make VERBOSE=1
  - cd ..
script: 
  - for f in build/pyQCD/tests/test_*; do echo "Running test file ${f}"; ./$f; done
  - py.test -vl
cache:
  directories:
  - $HOME/.pip-accel
