language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - cmake
    - libeigen3-dev
before_install:
  - pip install pip-accel
install:
  - pip-accel install -r requirements.txt
  - pip install .
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - cd ..
script: 
  - for f in build/pyQCD/test_*; do echo "Running test file ${f}"; ./$f; done
  - py.test -vl
cache:
  directories:
  - $HOME/.pip-accel
