language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libeigen3-dev
before_install:
  - pip install pip-accel
install:
  - pip-accel install -r requirements.txt
  - "CC=clang CXX=clang++ pip install ."
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  - make
  - cd ..
script: 
  - build/pyQCD/tests/run_tests
  - py.test -vl
cache:
  directories:
  - $HOME/.pip-accel
